# Shell variables
# Generated by 'wal'
wallpaper='/home/birkhoff/Images/wallhaven-r25exq.jpg'

# Special
background='#011B34'
foreground='#dbe4ca'
cursor='#dbe4ca'

# Colors
color0='#011B34'
color1='#90AC29'
color2='#A7C93B'
color3='#98AB5A'
color4='#AECB61'
color5='#A8B4A8'
color6='#B5CC9C'
color7='#dbe4ca'
color8='#999f8d'
color9='#90AC29'
color10='#A7C93B'
color11='#98AB5A'
color12='#AECB61'
color13='#A8B4A8'
color14='#B5CC9C'
color15='#dbe4ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
