--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/birkhoff/Images/wallhaven-r25exq.jpg"

-- Special
background="#011B34"
foreground="#dbe4ca"
cursor="#dbe4ca"

-- Colors
color0="#011B34"
color1="#90AC29"
color2="#A7C93B"
color3="#98AB5A"
color4="#AECB61"
color5="#A8B4A8"
color6="#B5CC9C"
color7="#dbe4ca"
color8="#999f8d"
color9="#90AC29"
color10="#A7C93B"
color11="#98AB5A"
color12="#AECB61"
color13="#A8B4A8"
color14="#B5CC9C"
color15="#dbe4ca"
