#!/bin/bash

## By Birkhoff

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -10 -yoffset -40 -width 13 -hide-scrollbar -line-padding 4 -padding 25 -lines 5 <<< "> Lock|> Suspend|> Hibernate|> Reboot|> Shutdown")"
            case "$MENU" in
                *Lock) ~/.bin/blurlock ;;
		*Suspend) systemctl suspend ;;
		*Hibernate) systemctl hibernate ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
